[package]
name = "monolithic-server"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.7"
fern = { version = "0.6.2", features = ["colored"] }
humantime = "2.1.0"
log = "0.4.22"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
socketioxide = { version = "0.14.1", features = ["state"] }
tokio = { version = "1.40.0", features = ["full"] }
